# Generated by Django 5.2.4 on 2025-08-25 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('village', models.CharField(db_index=True, max_length=100)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('medical_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('is_guardian', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rescue.guardian')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='rescue_fami_name_9c81ab_idx'), models.Index(fields=['mobile_number'], name='rescue_fami_mobile__901125_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_guardian', True)), fields=('guardian',), name='unique_guardian_member_per_guardian')],
            },
        ),
    ]
